apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: monitors.newrelic.shanestarcher.com
spec:
  group: newrelic.shanestarcher.com
  names:
    kind: Monitor
    listKind: MonitorList
    plural: monitors
    singular: monitor
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Monitor is the Schema for the monitors API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MonitorSpec defines the desired state of Monitor
          properties:
            conditions:
              items:
                properties:
                  policyName:
                    type: string
                  runbookURL:
                    type: string
                type: object
              type: array
            frequency:
              format: int64
              type: integer
            locations:
              items:
                type: string
              type: array
            manageUpdates:
              type: boolean
            options:
              properties:
                bypassHEADRequest:
                  type: boolean
                treatRedirectAsFailure:
                  type: boolean
                validationString:
                  type: string
                verifySSL:
                  type: boolean
              type: object
            script:
              description: TODO flatten this structure out
              properties:
                scriptText:
                  type: string
              type: object
            slaThreshold:
              type: string
            status:
              type: string
            type:
              type: string
            uri:
              type: string
          type: object
        status:
          properties:
            hash:
              format: byte
              type: string
            id:
              type: string
            info:
              type: string
          type: object
      required:
      - metadata
      - spec
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
