name: Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build -t image .

    - uses: anchore/scan-action@master
      with:
        image-reference: image
        dockerfile-path: Dockerfile
        fail-build: true
        include-app-packages: true
